# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConnectFour' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Google-Mobile-Ads-SDK'

  target 'ConnectFourTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConnectFourUITests' do
    # Pods for testing
  end

end
